### ISSUE TITLE
[BUG] <title> Youtube Player keeps buffering

### ISSUE THREAD

**Issue by Gosplex** [sarbagyastha/youtube_player_flutter#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package

youtube_player_flutter

### What happened?

The Youtube player keeps buffering and never players. Also some inappwebview **SUPPRESS_ERROR_PAGE** error

### What is the expected behaviour?

Youtube video is supposed to play.

### How to reproduce?

1. In Windows, Android
2. Error:

E/chromium(25062): [ERROR:simple_backend_impl.cc(767)] Simple Cache Backend: cache directory inaccessible right after creation; path: /data/user/0/com.meetmighty.era/cache/WebView/Default/HTTP Cache/Code Cache/js
E/chromium(25062): [ERROR:simple_backend_impl.cc(767)] Simple Cache Backend: cache directory inaccessible right after creation; path: /data/user/0/com.meetmighty.era/cache/WebView/Default/HTTP Cache/Code Cache/wasm
E/chromium(25062): [ERROR:disk_cache.cc(208)] Unable to create cache
E/chromium(25062): [ERROR:disk_cache.cc(208)] Unable to create cache
D/CompatibilityChangeReporter(25062): Compat change id reported: 214741472; UID 10521; state: ENABLED
D/CompatibilityChangeReporter(25062): Compat change id reported: 171228096; UID 10521; state: ENABLED
D/InAppWebView(25062): Using InAppWebViewClientCompat implementation
W/cr_WebSettings(25062): setForceDark() is a no-op in an app with targetSdkVersion>=T
W/cr_SupportWebSettings(25062): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views(25062): Failed to handle method call
E/MethodChannel#flutter/platform_views(25062): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views(25062): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views(25062): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views(25062): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views(25062): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views(25062): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views(25062): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(25062): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(25062): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter/platform_views(25062): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(25062): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter/platform_views(25062): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter/platform_views(25062): 	at android.app.ActivityThread.main(ActivityThread.java:8394)
E/MethodChannel#flutter/platform_views(25062): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(25062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
E/MethodChannel#flutter/platform_views(25062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E/flutter (25062): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter (25062): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter (25062): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter (25062): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter (25062): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter (25062): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter (25062): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter (25062): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/flutter (25062): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/flutter (25062): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter (25062): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter (25062): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (25062): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (25062): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (25062): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (25062): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter (25062): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (25062): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter (25062): 	at android.os.Looper.loop(Looper.java:294)
E/flutter (25062): 	at android.app.ActivityThread.main(ActivityThread.java:8394)
E/flutter (25062): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
E/flutter (25062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E/flutter (25062): )
E/flutter (25062): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (25062): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (25062): <asynchronous suspension>
E/flutter (25062): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1104:5)
E/flutter (25062): <asynchronous suspension>
E/flutter (25062): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:827:5)
E/flutter (25062): <asynchronous suspension>
E/flutter (25062): 

### Flutter Doctor Output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.5131], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.95.3)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

**Comment by Gosplex** [comment]
No, I had to downgrade the package version and it worked

**Comment by ndevev** [comment]
> No, I had to downgrade the package version and it worked

To which version?

**Comment by muhitmahmudbs23** [comment]
Issue is fixed in the latest version (9.1.1) 

> > No, I had to downgrade the package version and it worked
> 
> To which version?
