### ISSUE TITLE
[BUG] Unable to load asset: packages/youtube_player_flutter/assets/speedometer.webp

### ISSUE THREAD

**Issue by sfratini** [sarbagyastha/youtube_player_flutter#138]
**Describe the bug**
As soon as the page loads, you can see the following error and stacktrace. 

**To Reproduce**
Just the example code from the readme will trigger this issue for me. 

**Expected behavior**
The video plays normally. 

**Technical Details:**
 - Device: Android Emulator Pixel 3 XL
 - OS: Android API 28

**Additional context**
It might be related to the following bug, as I get the same error after trying to Play the video. Since nobody posted the stacktrace, I have to assume they are non related, but could be. 
https://github.com/sarbagyastha/youtube_player_flutter/issues/120

```
E/flutter ( 9723): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 9723): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:91)
E/flutter ( 9723): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter ( 9723): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter ( 9723): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter ( 9723): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter ( 9723): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter ( 9723): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9723): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 9723): 	at android.os.Looper.loop(Looper.java:160)
E/flutter ( 9723): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter ( 9723): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9723): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 9723): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 9723): , null)
E/flutter ( 9723): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9723): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 9723): <asynchronous suspension>
E/flutter ( 9723): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter ( 9723): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter ( 9723): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter ( 9723): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter ( 9723): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter ( 9723): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 9723): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 9723): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 9723): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter ( 9723): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #15     RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:520:13)
E/flutter ( 9723): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 9723): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter ( 9723): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 9723): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 9723): #24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter ( 9723): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter ( 9723): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #28     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter ( 9723): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 9723): #30     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter ( 9723): #31     RenderObject.layout (package

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/youtube_player_flutter/assets/speedometer.webp

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:484:44)
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:469:14)
#3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
...
Image provider: AssetImage(bundle: null, name: "packages/youtube_player_flutter/assets/speedometer.webp")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#a0ccc(), name: "packages/youtube_player_flutter/assets/speedometer.webp", scale: 1.0)
```

**Comment by sfratini** [comment]
I think this was happening because I forgot to clean and build again. Working fine now, sorry.

**Comment by AbdurRehman-coder** [comment]
Just run this command.
`flutter clean && flutter run`
it will solve your problem
