### ISSUE TITLE
Video is not displaying

### ISSUE THREAD

**Issue by senthilkumar88** [sarbagyastha/youtube_player_flutter#19]
First thank you for this library. I just tried the sample code provided audio is working but video is not displaying.
![image](https://user-images.githubusercontent.com/6154302/57985493-6a59ff00-7a86-11e9-905f-6dbe1a87bbbd.png)

**Comment by senthilkumar88** [comment]
First thank you for this library. I have tried the sample code given but the video is not displayed only audio is playing. 
![image](https://user-images.githubusercontent.com/6154302/57985336-dab35100-7a83-11e9-8e07-fcb4a05fc7cd.png)

**Comment by sarbagyastha** [comment]
It look quite weird, haven't found such issue yet. Can you confirm whether or not it is working with new update.

**Comment by nanshansuiyuan** [comment]
First thank you for this library. I met the same trouble.Something in detail
1、 I tried the apk and it did not work in my phone which is Huawei NOVA.(it seems that  cannot access the url  "https://sarbagyadhaubanjar.github.io/youtube_player")
2、I tried to run the example but it did not work either
3、I tried to run the main.dart in my project which has changed the dependencies but it also got some trouble. (I am in China so change the google dependencies  to Alibaba)
message:
09:25:23.463 2087 info flutter.tools [   +5 ms] I/flutter ( 4115): The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#435f3):
09:25:23.463 2088 info flutter.tools [        ] I/flutter ( 4115): A non-null String must be provided to a Text widget.
09:25:23.463 2089 info flutter.tools [        ] I/flutter ( 4115): 'package:flutter/src/widgets/text.dart': Failed assertion: line 241 pos 10: 'data != null'

I have no idea what is going on,would you mind giving me  a hand, thank you  so much.

**Comment by sarbagyastha** [comment]
Can you attach full log output ?

**Comment by nanshansuiyuan** [comment]
the full log saved in the file, thank you for kind help.


------------------ 原始邮件 ------------------
发件人: "Sarbagya Dhaubanjar"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 晚上11:56
收件人: "sarbagyastha/youtube_player_flutter"<youtube_player_flutter@noreply.github.com>;
抄送: "流年非也"<1090856727@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [sarbagyastha/youtube_player_flutter] Video is not displaying(#19)




Can you attach full log output ?

**Comment by sarbagyastha** [comment]
Which file @nanshansuiyuan :confused: ?

**Comment by nanshansuiyuan** [comment]
My big pardon,see the additional file
I have put it last email   I have no idea if you can receive it or not


------------------ 原始邮件 ------------------
发件人: "Sarbagya Dhaubanjar"<notifications@github.com>;
发送时间: 2019年6月9日(星期天) 中午1:57
收件人: "sarbagyastha/youtube_player_flutter"<youtube_player_flutter@noreply.github.com>;
抄送: "流年非也"<1090856727@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [sarbagyastha/youtube_player_flutter] Video is not displaying(#19)




Which file @nanshansuiyuan  ?

**Comment by akinsete** [comment]
Video not playing as well

**Comment by sarbagyastha** [comment]
Sorry for late response, but haven't got your attachments. It won't attach file if you replyto github notifications through mail.
Please send it to `github@sarbagyastha.com.np` instead.

**Comment by malder08** [comment]
I'm having the same issue. Audio is working and I can see all of the controls but no video.

**Comment by andrescr94** [comment]
Same thing, a white screen no video but audio and controls work. Huawei Mate10

**Comment by rlee1990** [comment]
I have the same issue using a Samsung Galaxy s10+

**Comment by phattranky** [comment]
Same on Android 24. Look like it shows a small thumbnail when I pause the video

I just clone the whole example. Even on iOS the video cannot play

<img width="1439" alt="main dart — learning_english_with_song 2019-07-07 17-56-20" src="https://user-images.githubusercontent.com/6443154/60767318-ab62ad00-a0e0-11e9-8466-af7e8295b13a.png">

**Comment by phattranky** [comment]
All my logs run as debug

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
D/EGL_emulation( 6393): eglMakeCurrent: 0xb2085d80: ver 2 0 (tinfo 0xb2083960)
D/        ( 6393): HostConnection::get() New Host Connection established 0xb2088400, tid 6406
W/System  ( 6393): ClassLoader referenced unknown path: /system/app/Chrome/lib/x86
I/WebViewFactory( 6393): Loading com.android.chrome version 51.0.2704.90 (code 275509012)
I/cr_LibraryLoader( 6393): Time to load native libraries: 15 ms (timestamps 5085-5100)
I/cr_LibraryLoader( 6393): Expected native library version number "51.0.2704.90", actual native library version number "51.0.2704.90"
V/WebViewChromiumFactoryProvider( 6393): Binding Chromium to main looper Looper (main, tid 1) {5417a3b}
I/cr_LibraryLoader( 6393): Expected native library version number "51.0.2704.90", actual native library version number "51.0.2704.90"
I/chromium( 6393): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_BrowserStartup( 6393): Initializing chromium process, singleProcess=true
E/ApkAssets( 6393): Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
E/ApkAssets( 6393): Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
D/EGL_emulation( 6393): eglCreateContext: 0x94c389c0: maj 2 min 0 rcv 2
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c389c0: ver 2 0 (tinfo 0x94c45ae0)
W/cr_media( 6393): Requires BLUETOOTH permission
D/cr_Ime  ( 6393): [InputMethodManagerWrapper.java:30] Constructor
W/cr_AwContents( 6393): onDetachedFromWindow called when already detached. Ignoring
D/cr_Ime  ( 6393): [InputMethodManagerWrapper.java:59] isActive: false
I/cr_Ime  ( 6393): ImeThread is not enabled.
E/libEGL  ( 6393): validate_display:99 error 3008 (EGL_BAD_DISPLAY)
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
I/VideoCapabilities( 6393): Unsupported profile 4 for video/mp4v-es
D/        ( 6393): HostConnection::get() New Host Connection established 0x83afc380, tid 6471
D/EGL_emulation( 6393): eglCreateContext: 0x83ab3420: maj 2 min 0 rcv 2
D/EGL_emulation( 6393): eglMakeCurrent: 0x83ab3420: ver 2 0 (tinfo 0x83a9b270)
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
I/art     ( 6393): Background sticky concurrent mark sweep GC freed 12768(625KB) AllocSpace objects, 2(40KB) LOS objects, 0% free, 14MB/14MB, paused 6.119ms total 44.349ms
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
W/cr_BindingManager( 6393): Cannot call determinedVisibility() - never saw a connection for the pid: 6393
D/cr_Ime  ( 6393): [InputMethodManagerWrapper.java:59] isActive: false
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 6393): eglMakeCurrent: 0x94c384e0: ver 2 0 (tinfo 0x8dc8b440)
D/        ( 6393): HostConnection::get() New Host Connection established 0x871fd340, tid 6480
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
D/        ( 6393): HostConnection::get() New Host Connection established 0xa2c7e500, tid 6405
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
E/EGL_emulation( 6393): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation( 6393): tid 6471: eglQueryContext(1716): error 0x3004 (EGL_BAD_ATTRIBUTE)
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6393): PlaybackQualityChange hd2160
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/OMXClient( 6393): MuxOMX ctor
V/cr_media( 6393): [MediaCodecBridge.java:572] createAudioTrack: sampleRate:48000 channelCount:2
D/AudioTrack( 6393): Client defaulted notificationFrames to 1731 for frameCount 3462
I/OMXClient( 6393): MuxOMX ctor
I/MediaCodec( 6393): [OMX.google.vp9.decoder] setting surface generation to 6546433
E/ACodec  ( 6393): [OMX.google.vp9.decoder] storeMetaDataInBuffers failed w/ err -1010
D/MediaPlayer( 6393): setSubtitleAnchor in MediaPlayer
W/art     ( 6393): Suspending all threads took: 9.436ms
I/art     ( 6393): Background partial concurrent mark sweep GC freed 64(1944B) AllocSpace objects, 2(5MB) LOS objects, 25% free, 11MB/15MB, paused 11.048ms total 131.125ms
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/art     ( 6393): Background partial concurrent mark sweep GC freed 25(728B) AllocSpace objects, 2(5MB) LOS objects, 25% free, 11MB/15MB, paused 11.058ms total 64.352ms
D/MediaCodec( 6393): [OMX.google.vp9.decoder] setting dataspace on output surface to #10c60000
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
D/        ( 6393): HostConnection::get() New Host Connection established 0x7cffd2c0, tid 6502
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6393): VideoData {"duration":346.221,"videoUrl":"https://www.youtube.com/watch?v=iLnmTe5Q2Qw","availableQualityLevels":["hd2160","hd1440","hd1080","hd720","large","medium","small","tiny","auto"],"videoEmbedCode":"<iframe width=\"100\" height=\"100\" src=\"https://www.youtube.com/embed/\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"}
D/SoftwareRenderer( 6393): setting dataspace on output surface to #10c60000
W/AudioTrack( 6393): releaseBuffer() track 0x8a64ed00 disabled due to previous underrun, restarting
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec  ( 6393): [OMX.google.vp9.decoder] ERROR(0x80001001)
E/ACodec  ( 6393): signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 6
E/cr_media( 6393): Failed to dequeue output buffer
E/cr_media( 6393): java.lang.IllegalStateException
E/cr_media( 6393): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/cr_media( 6393): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2568)
E/cr_media( 6393): 	at org.chromium.media.MediaCodecBridge.dequeueOutputBuffer(MediaCodecBridge.java:416)
W/cr_media( 6393): calling MediaCodec.release()
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 0
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 0
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 0
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 0
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 0
E/MediaCodec( 6393): Codec reported err 0x80001001, actionCode 0, while in state 0
W/cr_media( 6393): calling MediaCodec.release()
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
E/EGL_emulation( 6393): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation( 6393): tid 6471: eglQueryContext(1716): error 0x3004 (EGL_BAD_ATTRIBUTE)
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6393): PlaybackQualityChange medium
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/OMXClient( 6393): MuxOMX ctor
V/cr_media( 6393): [MediaCodecBridge.java:572] createAudioTrack: sampleRate:48000 channelCount:2
D/AudioTrack( 6393): Client defaulted notificationFrames to 1731 for frameCount 3462
I/OMXClient( 6393): MuxOMX ctor
I/MediaCodec( 6393): [OMX.google.vp9.decoder] setting surface generation to 6546434
E/ACodec  ( 6393): [OMX.google.vp9.decoder] storeMetaDataInBuffers failed w/ err -1010
D/MediaCodec( 6393): [OMX.google.vp9.decoder] setting dataspace on output surface to #103
D/        ( 6393): HostConnection::get() New Host Connection established 0x7a37e140, tid 6530
D/SoftwareRenderer( 6393): setting dataspace on output surface to #103
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6393): VideoData {"duration":346.221,"videoUrl":"https://www.youtube.com/watch?t=28&v=iLnmTe5Q2Qw","availableQualityLevels":["hd2160","hd1440","hd1080","hd720","large","medium","small","tiny","auto"],"videoEmbedCode":"<iframe width=\"100\" height=\"100\" src=\"https://www.youtube.com/embed/\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"}
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6393): Attempt to remove non-JNI local reference, dumping thread
W/cr_media( 6393): calling MediaCodec.release()
W/cr_media( 6393): calling MediaCodec.release()

```

**Comment by phattranky** [comment]
This log when I run from the example I cloned at Master

```
Phat-Macbook:example phattran$ flutter packages get
Running "flutter packages get" in example...                        0.6s
Phat-Macbook:example phattran$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts,
consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                             30.4s
Resolving dependencies...                                          23.3s
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        45.3s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         1.6s
D/EGL_emulation( 6982): eglMakeCurrent: 0xb2085480: ver 2 0 (tinfo 0xb2083270)
D/        ( 6982): HostConnection::get() New Host Connection established 0x91c7f480, tid 6995
W/System  ( 6982): ClassLoader referenced unknown path: /system/app/Chrome/lib/x86
I/WebViewFactory( 6982): Loading com.android.chrome version 51.0.2704.90 (code 275509012)
D/        ( 6982): HostConnection::get() New Host Connection established 0xb2088100, tid 6996
I/cr_LibraryLoader( 6982): Time to load native libraries: 10 ms (timestamps 4789-4799)
I/cr_LibraryLoader( 6982): Expected native library version number "51.0.2704.90", actual native library version number "51.0.2704.90"
V/WebViewChromiumFactoryProvider( 6982): Binding Chromium to main looper Looper (main, tid 1) {8afcf56}
I/cr_LibraryLoader( 6982): Expected native library version number "51.0.2704.90", actual native library version number "51.0.2704.90"
I/chromium( 6982): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_BrowserStartup( 6982): Initializing chromium process, singleProcess=true
E/ApkAssets( 6982): Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
E/ApkAssets( 6982): Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
D/EGL_emulation( 6982): eglCreateContext: 0x93c4a040: maj 2 min 0 rcv 2 
D/EGL_emulation( 6982): eglMakeCurrent: 0x93c4a040: ver 2 0 (tinfo 0xae4cd360)
W/cr_media( 6982): Requires BLUETOOTH permission                        
D/cr_Ime  ( 6982): [InputMethodManagerWrapper.java:30] Constructor      
W/cr_AwContents( 6982): onDetachedFromWindow called when already detached. Ignoring
D/cr_Ime  ( 6982): [InputMethodManagerWrapper.java:59] isActive: false  
I/cr_Ime  ( 6982): ImeThread is not enabled.                            
E/libEGL  ( 6982): validate_display:99 error 3008 (EGL_BAD_DISPLAY)     
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 6982): eglMakeCurrent: 0x93c48480: ver 2 0 (tinfo 0xae4cdaf0)
I/VideoCapabilities( 6982): Unsupported profile 4 for video/mp4v-es     
D/EGL_emulation( 6982): eglMakeCurrent: 0x93c48480: ver 2 0 (tinfo 0xae4cdaf0)
D/        ( 6982): HostConnection::get() New Host Connection established 0x88fc2500, tid 7044
D/EGL_emulation( 6982): eglCreateContext: 0x8a18af80: maj 2 min 0 rcv 2 
I/art     ( 6982): Background sticky concurrent mark sweep GC freed 13098(818KB) AllocSpace objects, 6(120KB) LOS objects, 18% free, 8MB/10MB, paused 1.534ms total 133.591ms
D/EGL_emulation( 6982): eglMakeCurrent: 0x8a18af80: ver 2 0 (tinfo 0x8f7033a0)
D/NetworkSecurityConfig( 6982): No Network Security Config specified, using platform default
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 6982): eglMakeCurrent: 0x93c48480: ver 2 0 (tinfo 0xae4cdaf0)
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/cr_BindingManager( 6982): Cannot call determinedVisibility() - never saw a connection for the pid: 6982
D/cr_Ime  ( 6982): [InputMethodManagerWrapper.java:59] isActive: false  
Syncing files to device Android SDK built for x86...                    
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              D/        ( 6982): HostConnection::get() New Host Connection established 0x891c2340, tid 7021
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                              W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
Syncing files to device Android SDK built for x86...                                               2,889ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:61644/4KpOkOyI7ZM=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
E/EGL_emulation( 6982): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation( 6982): tid 7044: eglQueryContext(1716): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/flutter ( 6982): PlaybackQualityChange medium
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
I/OMXClient( 6982): MuxOMX ctor
D/MediaPlayer( 6982): setSubtitleAnchor in MediaPlayer
V/cr_media( 6982): [MediaCodecBridge.java:572] createAudioTrack: sampleRate:48000 channelCount:2
D/AudioTrack( 6982): Client defaulted notificationFrames to 1731 for frameCount 3462
I/OMXClient( 6982): MuxOMX ctor
I/MediaCodec( 6982): [OMX.google.vp9.decoder] setting surface generation to 7149569
E/ACodec  ( 6982): [OMX.google.vp9.decoder] storeMetaDataInBuffers failed w/ err -1010
D/MediaCodec( 6982): [OMX.google.vp9.decoder] setting dataspace on output surface to #103
D/        ( 6982): HostConnection::get() New Host Connection established 0x85cff840, tid 7081
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
D/SoftwareRenderer( 6982): setting dataspace on output surface to #103
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6982): PlaybackQualityChange hd1080
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
I/flutter ( 6982): PlaybackQualityChange hd1440
I/flutter ( 6982): PlaybackQualityChange hd2160
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
D/SoftwareRenderer( 6982): setting dataspace on output surface to #104
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
D/SoftwareRenderer( 6982): setting dataspace on output surface to #10c60000
W/art     ( 6982): Attempt to remove non-JNI local reference, dumping thread
```

cc: @sarbagyastha

**Comment by phattranky** [comment]
Confirm. It can working well on real Android Device. I tested on Samsung Galaxy A8 - 2018 with Android 9.0

But the real iPhone device still display blank after touch to Play. I tested on iPhone 6 with iOS 12.0

**Comment by sarbagyastha** [comment]
Colud you check whether or not the issue persists on new version ? My mac is out of order, so it would be nice if someone could submit full log.
