### ISSUE TITLE
Add link to workaround for https://github.com/flutter/flutter/issues/53076 in pub documentation

### ISSUE THREAD

**Issue by majorbriggs** [sarbagyastha/youtube_player_flutter#225]
When the player is used in an new Flutter project,

`RuntimeException 'Cannot execute operation because FlutterJNI is not attached to native' `
is thrown every the app closes (tested on Samsung Note 9 and emulators)

Interestingly, this error does not happen when running the example project from the repo - no idea why.

The workaround I found is to add to MainActivity onDestroy method (found in 
flutterEngine.getPlatformViewsController().onFlutterViewDestroyed() is called onDestroy of the activity.
(found here: https://github.com/flutter/flutter/issues/53076)

Maybe you mention this particular issue in the readme, or in installation notes, as it  is quite discouraging.

**Comment by Omi231** [comment]
@majorbriggs What flutter version do you have? In flutter 1.18 it is giving me error!

**Comment by majorbriggs** [comment]
I have the latest stable, 1.17.1.

The fix should include null safe calls (with ?.), I corrected the original comment.

**Comment by sarbagyastha** [comment]
Could you please test with v7.0.0 ?

**Comment by majorbriggs** [comment]
I tested  it with 7.0.0 and I'm getting the same error
` java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native`

Additionally the fix that I proposed above (that worked for 6.1.1) doesn't fix work on 7.0.0 anymore, on closing, the activity throws an exception, but a different one:

```
2020-06-19 16:18:15.052 1512-1512/com.majorbriggs.testnewytplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.majorbriggs.testnewytplayer, PID: 1512
    java.lang.RuntimeException: Unable to destroy activity {com.majorbriggs.testnewytplayer/com.majorbriggs.testnewytplayer.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5193)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5227)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:207)
        at io.flutter.embedding.android.FlutterView.onCreateInputConnection(FlutterView.java:517)
        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:2113)
        at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:2047)
        at io.flutter.embedding.android.FlutterView.detachFromFlutterEngine(FlutterView.java:788)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:442)
        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:575)
        at com.majorbriggs.testnewytplayer.MainActivity.onDestroy(MainActivity.kt:9)
        at android.app.Activity.performDestroy(Activity.java:8217)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5178)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5227) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
```
