### ISSUE TITLE
[BUG] Orientation change: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_0

### ISSUE THREAD

**Issue by brendabullorini** [sarbagyastha/youtube_player_flutter#242]
Video is loading fine when the app opens but then if I change device orientation, it stops the video and this error is shown:

E/flutter (17018): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_0)
E/flutter (17018): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (17018): <asynchronous suspension>
E/flutter (17018): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (17018): #2      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview_controller.dart:1137:31)
E/flutter (17018): #3      YoutubePlayerController._callMethod (package:youtube_player_flutter/src/utils/youtube_player_controller.dart:173:32)
E/flutter (17018): #4      YoutubePlayerController.mute (package:youtube_player_flutter/src/utils/youtube_player_controller.dart:224:18)
E/flutter (17018): #5      _YoutubePlayerState.listener (package:youtube_player_flutter/src/player/youtube_player.dart:211:45)
E/flutter (17018): #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:207:21)
E/flutter (17018): #7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:274:5)
E/flutter (17018): #8      YoutubePlayerController.updateValue (package:youtube_player_flutter/src/utils/youtube_player_controller.dart:181:52)
E/flutter (17018): #9      _RawYoutubePlayerState.build.<anonymous closure>.<anonymous closure> (package:youtube_player_flutter/src/player/raw_youtube_player.dart:198:28)
E/flutter (17018): #10     InAppWebViewController.handleMethod (package:flutter_inappwebview/src/in_app_webview_controller.dart:748:71)
E/flutter (17018): #11     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter (17018): #12     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter (17018): #13     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (17018): #14     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (17018): #15     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (17018): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (17018): #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (17018): #18     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (17018): #19     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)

Only test on Android

**Comment by brendabullorini** [comment]
Uhm. I just checked the example main.dart code on a new project and it seems to work fine there. So I'll check my project code to find what's going on.

**Comment by brendabullorini** [comment]
Solved it, just needed to wrap everything inside YoutubePlayerBuilder
