### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by duckieu1989** [sarbagyastha/youtube_player_flutter#244]
I/libOpenSLES( 7544): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
D/AudioTrack( 7544): Client defaulted notificationFrames to 240 for frameCount 480
D/AudioManager( 7544): requestAudioFocus status : 1
D/ViewRootImpl@e2b04b5[MainActivity]( 7544): Relayout returned: oldFrame=[0,0][1080,608] newFrame=[0,0][1080,608] result=0x1 surface={isValid=true -1232480256} surfaceGenerationChanged=false
E/chromium( 7544): [ERROR:web_contents_delegate.cc(218)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
E/chromium( 7544): [ERROR:web_contents_delegate.cc(218)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
W/cr_media( 7544): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/CameraManagerGlobal( 7544): Connecting to camera service
W/CameraBase( 7544): An error occurred while connecting to camera 1: Service not available
E/cr_VideoCapture( 7544): Camera.open: 
E/cr_VideoCapture( 7544): java.lang.RuntimeException: Fail to connect to camera service
E/cr_VideoCapture( 7544): 	at android.hardware.Camera.<init>(Camera.java:519)
E/cr_VideoCapture( 7544): 	at android.hardware.Camera.open(Camera.java:364)
E/cr_VideoCapture( 7544): 	at e13.g(chromium-Monochrome.aab-stable-410408370:1)
E/cr_VideoCapture( 7544): 	at org.chromium.media.VideoCaptureFactory.getDeviceSupportedFormats(chromium-Monochrome.aab-stable-410408370:2)
W/CameraBase( 7544): An error occurred while connecting to camera 0: Service not available
E/cr_VideoCapture( 7544): Camera.open: 
E/cr_VideoCapture( 7544): java.lang.RuntimeException: Fail to connect to camera service
E/cr_VideoCapture( 7544): 	at android.hardware.Camera.<init>(Camera.java:519)
E/cr_VideoCapture( 7544): 	at android.hardware.Camera.open(Camera.java:364)
E/cr_VideoCapture( 7544): 	at e13.g(chromium-Monochrome.aab-stable-410408370:1)
E/cr_VideoCapture( 7544): 	at org.chromium.media.VideoCaptureFactory.getDeviceSupportedFormats(chromium-Monochrome.aab-stable-410408370:2)

**Comment by sarbagyastha** [comment]
A reproducible example or snippet would be helpful
