### ISSUE TITLE
[BUG] Showing the Youtube Home Screen

### ISSUE THREAD

**Issue by Medrov** [sarbagyastha/youtube_player_flutter#312]
**Describe the bug**
Hey, what's dudes. I have some problem with playing video within my app. The bug emerge, when I am trying to play my video and in logs I get this:

> flutter: Instance of 'ASN1ParseError'
> flutter: #0      X509Certificate.fromDerData (package:flutter_inappwebview/src/X509Certificate/x509_certificate.dart:58)
> #1      X509Certificate.fromData (package:flutter_inappwebview/src/X509Certificate/x509_certificate.dart:42)
> #2      InAppWebViewController.handleMethod (package:flutter_inappwebview/src/in_app_webview_controller.dart:476)
> #3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:432)
> #4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:385)
> #5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267)
> #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:298)
> #7      _rootRun (dart:async/zone.dart:1190)
> #8      _CustomZone.run (dart:async/zone.dart:1093)
> #9      _CustomZone.runGuarded (dart:async/zone.dart:997)
> #10     _invoke3 (dart:ui/hooks.dart:297)
> #11     _dispatchPlatformMessage (dart:ui/hooks.dart:172)
> 
And I use ordibary code from example. But the main problem is the app shows Youtube Home Screen instead of video however on Android works perfectly without bugs

**Screenshots**
![photo_2020-07-30_11-17-15](https://user-images.githubusercontent.com/43564622/88925340-11d2e400-d27d-11ea-94d6-6d5f6d317dab.jpg)

**Technical Details:**
 - Device: [iPad]
 - OS: [iOS 11]
 - Version [7.0.0+7]

**Comment by nteko** [comment]
Same here.
It also happens on iPhone(real device, not simulator) two.

**Comment by Uvelir** [comment]
The same happened to me on iOS, package version 7.0.0+7
