### ISSUE TITLE
Live Videos Still not working on iOS

### ISSUE THREAD

**Issue by kaumudpa** [sarbagyastha/youtube_player_flutter#51]
Live Videos are still not working on iOS

**Comment by sarbagyastha** [comment]
Could you check if  [**Version 4.1.0**](https://pub.dev/packages/youtube_player_flutter#410) fix it?

**Comment by kaumudpa** [comment]
@sarbagyastha 
Na - even V4.1.0 is not working, Unable to play live videos or even the default video on iOS- This is the log i get when i press on play! : 

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:601:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:553:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:565:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#18     _rootRunUnary (dart:async/zone.dart:1136:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _invoke1 (dart:ui/hooks.dart:250:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
```

**Comment by vinodlee** [comment]
Same problem for me

**Comment by sarbagyastha** [comment]
Check #79
