### ISSUE TITLE
Cannot run the exapmple in Web [BUG]

### ISSUE THREAD

**Issue by praharshbhatt** [sarbagyastha/youtube_player_flutter#514]
**Describe the bug**
Error when Loading videos on web
**To Reproduce**
flutter run web (youtube_player_iframe)

**Expected behavior**
Videos load and play successfully

**Logs**
```
Error: Expected a value of type 'int', but got one of type 'String'
    at Object.throw_ [as throw] (http://localhost:57336/dart_sdk.js:5041:11)
    at Object.castError (http://localhost:57336/dart_sdk.js:5014:15)
    at Object.cast [as as] (http://localhost:57336/dart_sdk.js:5323:17)
    at Function.as (http://localhost:57336/dart_sdk.js:18072:19)
    at http://localhost:57336/packages/youtube_player_iframe/src/helpers/youtube_value_builder.dart.lib.js:517:105
    at Object._checkAndCall (http://localhost:57336/dart_sdk.js:5246:16)
    at Object.dcall (http://localhost:57336/dart_sdk.js:5251:17)
    at http://localhost:57336/dart_sdk.js:100646:100
```

**Comment by Chandan-CV** [comment]
Greetings!
since you closed this issue, I am assuming that you have solved this bug.
if yes, can you share the solution? I am facing the same issue.

thank you
