### ISSUE TITLE
[BUG] Android - Error to load the video at Flutter 2.10 version. Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Sending touch to an unknown view with id: 0)

### ISSUE THREAD

**Issue by thiagocarvalhodev** [sarbagyastha/youtube_player_flutter#611]
In the Flutter >= 2.10 the video player shows nothing, even using the example project.

I tested the same example project with the 2.8.0 version and it works fine. So, I assume that in version 2.10 there's some problem.

To reproduce:
Try to run the example project with 2.10 or a newer version.

It will throws the following exception:

E/flutter (32310): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Sending touch to an unknown view with id: 0
E/flutter (32310):      at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:317)
E/flutter (32310):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:176)
E/flutter (32310):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
E/flutter (32310):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (32310):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter (32310):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter (32310):      at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
E/flutter (32310):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (32310):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (32310):      at android.os.Looper.loop(Looper.java:223)
E/flutter (32310):      at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (32310):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32310):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (32310):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (32310): , null, null)
E/flutter (32310): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (32310): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (32310): <asynchronous suspension>
E/flutter (32310): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:803:5)
E/flutter (32310): <asynchronous suspension>
E/flutter (32310): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:895:7)
E/flutter (32310): <asynchronous suspension>
E/flutter (32310): 

It is expected to show the video but shows nothing:

![image](https://user-images.githubusercontent.com/32248947/154121767-d34fa87b-6ef7-44b8-bd05-e797e8ca159c.png)

 - Device: [Nexus API  30]
 - Version [2.2.2]

**Comment by swenhancer** [comment]
It works for me on Flutter Channel stable, 2.10.2, on macOS 12.2.1.

**Comment by msatriowibowo** [comment]
Also works for me on Flutter Channel Stable, 2.10.2, on Android 11.
