### ISSUE TITLE
[BUG] Exception thrown for a url that points to non-existing video

### ISSUE THREAD

**Issue by sunilguptasg** [sarbagyastha/youtube_player_flutter#635]
**Describe the bug**
A YouTube link that no longer exists throws error here:

            if (data.containsKey('Errors')) {
              controller.add(
                controller.value
                    .copyWith(error: errorEnum(data['Errors'] as int)),
              );
            }

Error: Expected a value of type 'int', but got one of type 'String'
    at Object.throw_ [as throw] (http://localhost:61972/dart_sdk.js:5067:11)
    at Object.castError (http://localhost:61972/dart_sdk.js:5026:15)
    at Object.cast [as as] (http://localhost:61972/dart_sdk.js:5351:17)
    at Function.as (http://localhost:61972/dart_sdk.js:19857:19)
at http://localhost:61972/packages/youtube_player_iframe/src/helpers/youtube_value_builder.dart.lib.js:535:105
    at Object._checkAndCall (http://localhost:61972/dart_sdk.js:5274:16)
    at Object.dcall (http://localhost:61972/dart_sdk.js:5279:17)
    at http://localhost:61972/dart_sdk.js:109327:100

**To Reproduce**
Take a valid URL and change one character of the videoID
example: https://www.youtube.com/watch?v=K7kO0zUeVUK 

**Expected behavior**
There should be no exception / user should have option to specify fallback URL

**Comment by sunilguptasg** [comment]
For now, I am validating the videoId in advance - however this method is risky as during the time gap between the validation and actual play, the video may no longer be available.

This method basically attempts to get the video thumbnail and uses the statuscode==200 as a success flag.

**
Future<bool> validateYouTubeUrl(String youTubeId) async {
  final Uri uri = Uri.http('img.youtube.com', '/vi/$youTubeId/default.jpg');

  try {
    final value = await http.get(uri, headers: {'Accept': '*/*'});
    if (value.statusCode == 200) {
      return true;
    }
  } catch (e) {
    debugPrint(e.toString());
  }
  return false;
}
**
