### ISSUE TITLE
[youtube_player_iframe]: example app crashes on API 19

### ISSUE THREAD

**Issue by deepak786** [sarbagyastha/youtube_player_flutter#661]
I ran the [example app ](https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe/example) on Android API 19 (OS 4.4).

It is crashing and getting the following exception:
```
E/AndroidRuntime( 2735): FATAL EXCEPTION: main
E/AndroidRuntime( 2735): Process: np.com.sarbagyastha.youtube_player_iframe_example, PID: 2735
E/AndroidRuntime( 2735): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 2735): 	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
E/AndroidRuntime( 2735): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
E/AndroidRuntime( 2735): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
E/AndroidRuntime( 2735): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView.prepare(InAppWebView.java:185)
E/AndroidRuntime( 2735): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:94)
E/AndroidRuntime( 2735): 	at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:32)
E/AndroidRuntime( 2735): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/AndroidRuntime( 2735): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/AndroidRuntime( 2735): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/AndroidRuntime( 2735): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 2735): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 2735): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 2735): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime( 2735): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2735): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2735): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2735): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 2735): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2735): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2735): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2735): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2735): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
E/AndroidRuntime( 2735): 	at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:243)
E/AndroidRuntime( 2735): 	at okhttp3.internal.platform.Platform.findAndroidPlatform(Platform.java:247)
E/AndroidRuntime( 2735): 	at okhttp3.internal.platform.Platform.findPlatform(Platform.java:203)
E/AndroidRuntime( 2735): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
E/AndroidRuntime( 2735): 	... 22 more
```

But it is mentioned that it should work on at least 17
https://pub.dev/packages/youtube_player_iframe#android

**Comment by sarbagyastha** [comment]
@deepak786 Please read the Notes, just below it.

**Comment by deepak786** [comment]
The note says that the video will not play which is fine. But the app is crashing which should not happen.

**Comment by deepak786** [comment]
flutter_inappwebview in Android uses the okhttp library version 3.14.9
https://github.com/pichillilorenzo/flutter_inappwebview/blob/ee1b0d7ff754a49e9f995c68505da3556b9c830d/android/build.gradle#L51

Starting from v3.13, okhttp requires Lollipop and above.
So this is the reason for the crash.

**Comment by sarbagyastha** [comment]
The new version uses `webview_flutter` instead. So, there is no such issue currently.
