### ISSUE TITLE
[BUG] Can't load videoById from Android

### ISSUE THREAD

**Issue by wer-mathurin** [sarbagyastha/youtube_player_flutter#684]
**Describe the bug**
Got this error on Android when trying to play the videoId => **MZEMdI-sxOo**
BTW this is working as expected when running it on the Web.

![image](https://user-images.githubusercontent.com/39314023/185638536-3ecba945-aed0-4587-8b19-761a8eb545b4.png)

I can see this in the flutter console:
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')

even enabling the debug in the WebView I didn't get much more detail when inspecting it
```
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at onReady ((index):55:45)
    at n.da (www-widgetapi.js:468:277)
    at go (www-widgetapi.js:991:52)
    at n.Ka (www-widgetapi.js:1020:318)
    at www-widgetapi.js:979:215
    at Vh.g (www-widgetapi.js:565:28)
```

**To Reproduce**
```
import 'package:flutter/material.dart';
import 'package:youtube_player_iframe/youtube_player_iframe.dart';

class VideoWidget extends StatefulWidget {
  const VideoWidget({required this.videoId, super.key});

  final String videoId;

  @override
  State<VideoWidget> createState() => _VideoWidgetState();
}

class _VideoWidgetState extends State<VideoWidget> {
  late final YoutubePlayerController _controller;

  @override
  void initState() {
    super.initState();

    _controller = YoutubePlayerController(
        params: const YoutubePlayerParams(
      loop: false,
      showControls: false,
      showFullscreenButton: false,
      strictRelatedVideos: true,
    ))
      ..onInit = () async {
        print(widget.videoId);
        await _controller.loadVideoById(
            videoId: widget.videoId, startSeconds: 0);
      };
  }

  @override
  Widget build(BuildContext context) {
    final player = YoutubePlayerIFrame(
      controller: _controller,
      gestureRecognizers: const {},
    );

    return YoutubePlayerControllerProvider(
      controller: _controller,
      child: Column(
        children: [
          player,
        ],
      ),
    );
  }
}
```

**Technical Details:**
 - Device:  Pixel 6 
 - OS: Android

**Additional context**
Using the version 3.0.3 of the plugin

**Comment by sarbagyastha** [comment]
It's because of `showControls` being `false`. Working on the fix.
