### ISSUE TITLE
Fatal Exception: java.lang.AssertionError Manager has already been closed.

### ISSUE THREAD

**Issue by rohansohonee** [sarbagyastha/youtube_player_flutter#701]
**Describe the bug**
After updating to v3 the following fatal crash is being reported.

```
Fatal Exception: java.lang.AssertionError
Manager has already been closed.

Fatal Exception: java.lang.AssertionError: Manager has already been closed.
       at io.flutter.plugins.webviewflutter.InstanceManager.assertManagerIsNotClosed(InstanceManager.java:9)
       at io.flutter.plugins.webviewflutter.InstanceManager.getIdentifierForStrongReference(InstanceManager.java)
       at io.flutter.plugins.webviewflutter.JavaScriptChannelFlutterApiImpl.getIdentifierForJavaScriptChannel(JavaScriptChannelFlutterApiImpl.java:2)
       at io.flutter.plugins.webviewflutter.JavaScriptChannelFlutterApiImpl.postMessage(JavaScriptChannelFlutterApiImpl.java)
       at io.flutter.plugins.webviewflutter.JavaScriptChannel.lambda$postMessage$1(JavaScriptChannel.java:6)
       at io.flutter.plugins.webviewflutter.JavaScriptChannel.$r8$lambda$K7533Hqo0qg7ff56ym-eNCAOHa4(JavaScriptChannel.java)
       at io.flutter.plugins.webviewflutter.JavaScriptChannel$$InternalSyntheticLambda$2$942c86d1a51c05498444059a61e0d6ae7621f7cf7a614902a174f9ffedd43aed$0.run(JavaScriptChannel.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8302)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

**To Reproduce**
Unable to reproduce.

**Technical Details:**
Device
Brand:Xiaomi
Model:Redmi Note 10
Orientation: Portrait
Operating System
Version:Android 12
Orientation: Portrait
Rooted:No
Crash

**Dependency version**
youtube_player_iframe: 3.0.4

**Comment by rohansohonee** [comment]
Here are details of another device also:

Device
Brand:LGE
Model:LG Q6
Orientation: Portrait
Operating System
Version:Android 7.1.1
Orientation: Portrait
Rooted:No
Crash

**Comment by deepak-agendaboa** [comment]
any update on this issue?

**Comment by rohansohonee1** [comment]
This PR https://github.com/flutter/plugins/pull/6943 may fix this issue. webview_flutter_android: 3.1.3

This commit https://github.com/sarbagyastha/youtube_player_flutter/commit/a957a9499fe53414819bd415a94ec4c7446a3c44 uses the updated webview_flutter_android: 3.2.1 (previous version used in package was 3.1.1)
