### ISSUE TITLE
[BUG] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference

### ISSUE THREAD

**Issue by Happi3r** [sarbagyastha/youtube_player_flutter#713]
**Describe the bug**
I don't know why I can't control the player after getting java.lang.NullPointerException.

Log:
```
I/flutter (20180): PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
I/flutter (20180): 	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.evaluateJavascript(WebViewHostApiImpl.java:426)
I/flutter (20180): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$13(GeneratedAndroidWebView.java:948)
I/flutter (20180): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda21.onMessage(Unknown Source:2)
I/flutter (20180): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
I/flutter (20180): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
```

**Comment by zhuwei** [comment]
this is webview_flutter's bug

**Comment by AbdurRehman-coder** [comment]
I also use the YouTube_player_ifram, and it creates clash with flutter_webview, anyone solved this problem
