### ISSUE TITLE
Problem to load thumbnail

### ISSUE THREAD

**Issue by d-apps** [sarbagyastha/youtube_player_flutter#77]
When I open the dart file that have the youtube player widget I get this error, after try touching the play button the video starts ok.

Even if I pass a thumbnailUrl I get this error.

![WhatsApp Image 2019-10-04 at 15 02 17](https://user-images.githubusercontent.com/20110433/66229458-36d7e400-e6b8-11e9-8eed-662a0bfe5885.jpeg)

```
[INFO:CONSOLE(108)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl6mioSm/www-widgetapi.js (108)
E/flutter (24364): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HttpException: No valid statuscode. Statuscode was 404
E/flutter (24364): #0      BaseCacheManager.getFile (package:flutter_cache_manager/src/cache_manager.dart:120:11)
E/flutter (24364): <asynchronous suspension>
E/flutter (24364): #1      CachedNetworkImageState._animatedWidget (package:cached_network_image/src/cached_image_widget.dart:270:12)
E/flutter (24364): #2      CachedNetworkImageState.build (package:cached_network_image/src/cached_image_widget.dart:196:12)
E/flutter (24364): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter (24364): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter (24364): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (24364): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter (24364): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (24364): #8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4852:32)
E/flutter (24364): #9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
E/flutter (24364): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (24364): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (24364): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (24364): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (24364): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (24364): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (24364): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (24364): #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
E/flutter (24364): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (24364): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (24364): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (24364): #21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
E/flutter (24364): #22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
E/flutter (24364): #23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
E/flutter (24364): #24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter (24364): #25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
E/flutter (24364): #26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter (24364): #27     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (24364): #28     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24364): #29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24364): #30     _invoke (dart:ui/hooks.dart:249:10)
E/flutter (24364): #31     _drawFrame (dart:ui/hooks.dart:207:3)
```

**My wiget:**

```
YoutubePlayer(
            context: context,
            videoId: videoId,
            aspectRatio: 16 / 9,
            inFullScreen: false,
            flags: YoutubePlayerFlags(
              autoPlay: false,
              hideControls: false,
              isLive: false,
              showVideoProgressIndicator: true,
            ),
            onPlayerInitialized: (controller){
              var _controller = controller;
              _controller.addListener((){

              });
            },

      );
```

**Comment by BugsBunnyBR** [comment]
I have the same problem... I tried to workaround it in this branch
https://github.com/BugsBunnyBR/youtube_player_flutter/tree/workaround-thumbnail

I basically extracted a ThumbnailWidget and it fails to load a thumbnail resolution I will try to load a lower quality... that has a side effect of the video area blink.. but I think that is better than not showing a thumbnail at all.

**Comment by sarbagyastha** [comment]
Thank you for reporting, I'll soon fix this issue with a more modular player.

**Comment by sarbagyastha** [comment]
Fixed with Version 5.
