### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method init on channel sarbagyastha.com.np/youtubePlayer)

### ISSUE THREAD

**Issue by baptisteArnaud** [sarbagyastha/youtube_player_flutter#82]
I'm trying to play videos on iOS simulator (iPhone 11 Pro max)

And I have right away this error:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel sarbagyastha.com.np/youtubePlayer)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      _channel (package:youtube_player/youtube_player.dart:42:9)
#2      _channel (package:youtube_player/youtube_player.dart:40:21)
#3      YoutubePlayer.keepOn (package:youtube_player/youtube_player.dart:861:36)
#4      _YoutubePlayerState.build (package:youtube_player/youtube_player.dart:974:21)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)<…>
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method keepOn on channel sarbagyastha.com.np/youtubePlayer)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      YoutubePlayer.keepOn (package:youtube_player/youtube_player.dart:861:45)
#2      _YoutubePlayerState.build (package:youtube_player/youtube_player.dart:974:21)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
#9      Element.inflateWidget (package:flutter/sr<…>
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel sarbagyastha.com.np/youtubePlayer)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      VideoPlayerController.initialize (package:youtube_player/youtube_player.dart:239:59)
<asynchronous suspension>
#2      _YoutubePlayerState.initializeYTController (package:youtube_player/youtube_player.dart:937:22)
#3      _YoutubePlayerState.build (package:youtube_player/youtube_player.dart:1002:7)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:<…>
```

I tried so many things... flutter clean etc..

I added this line in Info.plist
```
<key>io.flutter.embedded_views_preview</key>
<string>YES</string>
```

Any ideas ?

**Comment by sarbagyastha** [comment]
The issue you reported about is another plugin, which only supports Android. So there's no implementation of the plugin on iOS.
