### ISSUE TITLE
[BUG] Crash app when click youtube (Android)

### ISSUE THREAD

**Issue by jaiendev** [sarbagyastha/youtube_player_flutter#847]
**Describe the bug**
When playing youtube -> Then select youtube to switch to watching youtube on the web -> When returning, the app crashes.

**Technical Details:**
 - Device: Redmi Note 11
 - OS: Android
 - Version: 12

**Comment by FaisalMohammadi** [comment]
i am facing the same when i come back i get this error Cannot add new events after calling close
**the whole error looks like this**:
`I/flutter (20436): Bad state: Cannot add new events after calling close
I/flutter (20436): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
I/flutter (20436): #1      YoutubePlayerController.update (package:youtube_player_iframe/src/controller/youtube_player_controller.dart:348:22)
I/flutter (20436): #2      YoutubePlayerEventHandler.onStateChange (package:youtube_player_iframe/src/controller/youtube_player_event_handler.dart:79:18)
I/flutter (20436): #3      YoutubePlayerEventHandler.call (package:youtube_player_iframe/src/controller/youtube_player_event_handler.dart:41:29)
I/flutter (20436): #4      new AndroidJavaScriptChannelParams.<anonymous closure>.<anonymous closure> (package:webview_flutter_android/src/android_webview_controller.dart:656:4`

**Comment by arshadabm** [comment]
I am also getting the same problem. Youtube video plays well, but after clicking on the back button, it crashed the app.
It shows the below error:

`Abort message: '[FATAL:flutter/shell/platform/android/surface_texture_external_texture.cc(56)] Check failed: state_ == AttachmentState::kAttached. 
'
    x0  0000000000000000  x1  0000000000002c45  x2  0000000000000006  x3  0000007fded4c210
    x4  00000072c4f90000  x5  00000072c4f90000  x6  00000072c4f90000  x7  000000000f1ea8e6
    x8  00000000000000f0  x9  0335135306935012  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 0000000000000085  x14 0000000000000000  x15 000055e2c7616e50
    x16 00000072be109948  x17 00000072be0e82d0  x18 00000072c46e0000  x19 0000000000002c45
    x20 0000000000002c45  x21 00000000ffffffff  x22 0000007222ca6818  x23 000000718bdfaf68
    x24 0000007fded4c878  x25 00000072240f2418  x26 0000000000000001  x27 0000000000000001
    x28 0000000000000042  x29 0000007fded4c290
    lr  00000072be09bca4  sp  0000007fded4c1f0  pc  00000072be09bcd0  pst 0000000000000000
backtrace:
      #00 pc 0000000000089cd0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 698b6aef520f034a9d40736d477f7a96)
      #01 pc 0000000001b98050  /data/app/~~cQR32SmHmFm7nReOh_k0dA==/freemovieshub.hd.club-ZwlqoOt6ooyw_iXr9VCeoQ==/lib/arm64/libflutter.so (BuildId: 3e777a7c19ec6d7aafc795b6e1e47a8ace70a2c6)`

**Comment by CanArslanDev** [comment]
Same error

```
I/flutter (31503): A YoutubePlayerController was used after being disposed.
I/flutter (31503): Once you have called dispose() on a YoutubePlayerController, it can no longer be used.
I/flutter (31503): A YoutubePlayerController was used after being disposed.
I/flutter (31503): Once you have called dispose() on a YoutubePlayerController, it can no longer be used.
F/flutter (31503): [FATAL:flutter/shell/platform/android/surface_texture_external_texture.cc(56)] Check failed: state_ == AttachmentState::kAttached. 
F/libc    (31503): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 31503 (com.example.app), pid 31503 (com.example.app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.211212.001.B1/8023802:user/release-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2024-10-26 12:16:01.132766200+0000
```

**Comment by ps86developer** [comment]
any solution for this ?
