### ISSUE TITLE
The Youtube Controller dispose is giving an error

### ISSUE THREAD

**Issue by Amodh2022** [sarbagyastha/youtube_player_flutter#937]
A YoutubePlayerController was used after being disposed.
Once you have called dispose() on a YoutubePlayerController, it can no longer be used.
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:412:27)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
#4      YoutubePlayerController.updateValue (package:youtube_player_flutter/src/utils/youtube_player_controller.dart:181:52)
#5      _RawYoutubePlayerState.build.<anonymous closure>.<anonymous closure> (package:youtube_player_flutter/src/player/raw_youtube_player.dart:210:29)
#6      AndroidInAppWebViewController._handleMethod (package:flutter_inappwebview_android/src/in_app_webview/in_app_webview_controller.dart:1542:73)
#7      InternalChannelController.initMethodCallHandler.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:631:30)

This is the error what im getting when the dispose method is called

**Comment by chrisynchen** [comment]
Fixed here. @sarbagyastha could you please help me to take a look?
https://github.com/sarbagyastha/youtube_player_flutter/pull/936
