### ISSUE TITLE
[BUG] Video not loading when using both youtube_player_flutter and google_mobile_ads.

### ISSUE THREAD

**Issue by ashokavarthanan** [sarbagyastha/youtube_player_flutter#956]
I cannot use both 
```
  youtube_player_flutter: ^9.0.1
  google_mobile_ads: ^5.1.0
```
ads are showing fine.
but video not loading. when remove `google_mobile_ads` it works fine.
```
D/InAppWebView( 5186): Using InAppWebViewClientCompat implementation
W/cr_SupportWebSettings( 5186): setForceDark() is a no-op in an app with targetSdkVersion>=TW/cr_SupportWebSettings( 5186): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views( 5186): Failed to handle method call
E/MethodChannel#flutter/platform_views( 5186): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views( 5186):  at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views( 5186):  at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views( 5186):  at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views( 5186):  at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views( 5186):  at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views( 5186):  at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:525)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:170)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 5186):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 5186):  at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#flutter/platform_views( 5186):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 5186):  at android.os.Looper.loop(Looper.java:214)  
E/MethodChannel#flutter/platform_views( 5186):  at android.app.ActivityThread.main(ActivityThread.java:7156)
E/MethodChannel#flutter/platform_views( 5186):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 5186):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/MethodChannel#flutter/platform_views( 5186):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/flutter ( 5186): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter ( 5186):      at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter ( 5186):      at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter ( 5186):      at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter ( 5186):      at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter ( 5186):      at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter ( 5186):      at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter ( 5186):      at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:525)
E/flutter ( 5186):      at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:170)
E/flutter ( 5186):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 5186):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 5186):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 5186):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 5186):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)        
E/flutter ( 5186):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5186):      at android.os.Handler.handleCallback(Handler.java:873)
E/flutter ( 5186):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5186):      at android.os.Looper.loop(Looper.java:214)
E/flutter ( 5186):      at android.app.ActivityThread.main(ActivityThread.java:7156)        
E/flutter ( 5186):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5186):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter ( 5186):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)     
E/flutter ( 5186): )
E/flutter ( 5186): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 5186): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 5186): <asynchronous suspension>
E/flutter ( 5186): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
E/flutter ( 5186): <asynchronous suspension>
E/flutter ( 5186): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
E/flutter ( 5186): <asynchronous suspension>
E/flutter ( 5186):
```

**Comment by tuyennvt** [comment]
You can try this:

dependency_overrides:
  webview_flutter_android: 3.16.1

**Comment by ashokavarthanan** [comment]
> You can try this:
> 
> `dependency_overrides:` ` webview_flutter_android: 3.16.1`

Thanks. Now it works.
