### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by dattd38** [sarbagyastha/youtube_player_flutter#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package

youtube_player_flutter

### What happened?

The video cannot be played 

### What is the expected behaviour?

D/InAppWebView( 5235): Using InAppWebViewClientCompat implementation
W/cr_WebSettings( 5235): setForceDark() is a no-op in an app with targetSdkVersion>=T
W/cr_SupportWebSettings( 5235): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views( 5235): Failed to handle method call
E/MethodChannel#flutter/platform_views( 5235): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views( 5235): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views( 5235): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views( 5235): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views( 5235): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views( 5235): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views( 5235): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 5235): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 5235): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#flutter/platform_views( 5235): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 5235): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views( 5235): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views( 5235): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#flutter/platform_views( 5235): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 5235): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views( 5235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 5235): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter ( 5235): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter ( 5235): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter ( 5235): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter ( 5235): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter ( 5235): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter ( 5235): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter ( 5235): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/flutter ( 5235): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/flutter ( 5235): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 5235): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 5235): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 5235): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 5235): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 5235): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5235): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 5235): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5235): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 5235): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 5235): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter ( 5235): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5235): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 5235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 5235): )
E/flutter ( 5235): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 5235): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 5235): <asynchronous suspension>
E/flutter ( 5235): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
E/flutter ( 5235): <asynchronous suspension>
E/flutter ( 5235): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
E/flutter ( 5235): <asynchronous suspension>
E/flutter ( 5235): 

### How to reproduce?

import 'package:flick_video_player/flick_video_player.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

class VideoFeature extends StatefulWidget {
  const VideoFeature({super.key});

  @override
  State<VideoFeature> createState() => _VideoFeatureState();
}

class _VideoFeatureState extends State<VideoFeature> {
  final ExploreStore _exploreStore = getIt<ExploreStore>();
  FlickManager? flickManager;
  YoutubePlayerController? _youtubeController;
  bool isYoutubeUrl = false;

  @override
  void initState() {
    super.initState();
    isYoutubeUrl = _exploreStore.videoExplore?.mainImg
            ?.contains("https://www.youtube.com") ??
        false;
    if (isYoutubeUrl) {
      String? videoId = YoutubePlayer.convertUrlToId(
          _exploreStore.videoExplore?.mainImg ?? "");
      _youtubeController = YoutubePlayerController(
          initialVideoId: videoId ?? "",
          flags: const YoutubePlayerFlags(autoPlay: true, mute: true));
    } else {
      Uri videoUrl = Uri.parse(_exploreStore.videoExplore?.mainImg ?? "");
      if (!videoUrl.isAbsolute) {
        videoUrl = Uri.parse(
            '${Endpoints.baseUrl}/${_exploreStore.videoExplore?.mainImg!}');
      }
      flickManager = FlickManager(
          videoPlayerController: VideoPlayerController.networkUrl(videoUrl));
    }
  }

  @override
  void dispose() {
    flickManager?.dispose();
    _youtubeController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _exploreStore.videoExplore != null
        ? Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Nổi bật',
                style: AppTextStyles.title20B.copyWith(color: AppColors.ink500),
              ),
              16.height,
              ClipRRect(
                borderRadius: BorderRadius.circular(8.0),
                child: AspectRatio(
                  aspectRatio: 16 / 9,
                  child: isYoutubeUrl
                      ? (_youtubeController != null
                          ? YoutubePlayer(
                              controller: _youtubeController!,
                              showVideoProgressIndicator: true,
                              progressIndicatorColor: Colors.amber,
                              progressColors: const ProgressBarColors(
                                playedColor: Colors.amber,
                                handleColor: Colors.amberAccent,
                              ),
                              onReady: () {},
                            )
                          : const Center(child: CircularProgressIndicator()))
                      : (flickManager != null
                          ? FlickVideoPlayer(flickManager: flickManager!)
                          : const Center(child: CircularProgressIndicator())),
                ),
              ),
            ],
          ).paddingSymmetric(horizontal: 16)
        : 0.height;
  }
}

**Comment by DavorStajcer** [comment]
I have the same problem.

I'm trying to fix it with this 
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2150

**Comment by DavorStajcer** [comment]
@dattd38 This worked for me :)
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2150#issuecomment-2226883498

**Comment by ge0rge000** [comment]
i have solution that return video from youtybe without know that video come from youtybe and all quality work and other function contact me on whatsapp:+971557474526
