### ISSUE TITLE
[BUG] <title>package:flutter/src/widgets/navigator.dart': Failed assertion: line 5277 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by surajgju** [sarbagyastha/youtube_player_flutter#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package

youtube_player_flutter

### What happened?

i switch version from 8.1.2 to 9.0.3 and i am unable to navigate back to previous screen from screen where video is playing.

here log : he following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5277 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5277:12)
#3      Navigator.pop (package:flutter/src/widgets/navigator.dart:2573:27)
#4      _YoutubePlayerBuilderState.build.<anonymous closure> (package:youtube_player_flutter/src/widgets/youtube_player_builder.dart:77:23)

### What is the expected behaviour?

i should easily navigate back using icon button in leading app bar by Navigator.of(context).pop() .

### How to reproduce?

1.when tap on navigate back leading in appbar which is inside widget YoutubePlayerBuilder it throw the error Failed assertion: line 5277 pos 12: '!_debugLocked': is not true.
2. i think this is youtube_player_flutter issue since its showing in Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=2_bug.yml
3. i am writing back like this simple leading: IconButton(
icon: const Icon(Icons.arrow_back_ios), // Customize the icon as needed
onPressed: () => Navigator.of(context).pop(),
),

### Flutter Doctor Output

```shell
[[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by hayoungko** [comment]
I'm having the same problem.

**Comment by mashmir** [comment]
PopScope(
canPop: false,
onPopInvoked: (didPop) { // <== Replace this function with onPopInvokedWithResult: (didPop, result) as this has been deprecated
final controller = widget.player.controller;
if (controller.value.isFullScreen) {
widget.player.controller.toggleFullScreenMode();
} else {
Navigator.pop(context);
}
},
child: widget.player,
),
);
